import { requireAdmin } from "@/lib/auth";
import { updateFulfillment } from "./actions";

export default async function AdminOrders({ searchParams }: { searchParams: Promise<{ updated?: string; error?: string }> }) {
  const params = await searchParams;
  const { supabase } = await requireAdmin();
  const { data } = await supabase.from("orders").select("id,order_number,email,status,payment_status,total_amount,currency,created_at,shipping_carrier,tracking_number").order("created_at", { ascending: false }).limit(100);
  return <><div className="admin-title"><div><p>Fulfillment</p><h1>Orders</h1></div></div>{params.updated ? <div className="notice success">Fulfillment updated.</div> : null}{params.error ? <div className="notice error">Fulfillment change failed. Paid orders are required before shipping.</div> : null}<section className="admin-panel"><div className="catalog-admin-list">{data?.length ? data.map((order) => { const update = updateFulfillment.bind(null, order.id); return <form action={update} className="order-admin-row" key={order.id}><div><b>LE-{order.order_number}</b><small>{order.email} · ${(order.total_amount / 100).toFixed(2)} {order.currency.toUpperCase()}</small><span className={`status-pill ${order.payment_status}`}>{order.payment_status}</span></div><label>Status<select name="status" defaultValue={order.status}><option value="pending">Pending</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></label><label>Carrier<input name="carrier" defaultValue={order.shipping_carrier || ""} placeholder="USPS" /></label><label>Tracking<input name="trackingNumber" defaultValue={order.tracking_number || ""} /></label><button className="admin-secondary" type="submit">Save</button></form>; }) : <p className="admin-empty">No orders yet. Orders will be created only by the server checkout flow.</p>}</div></section></>;
}
