import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ImagePlus, Star, Trash2 } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { addVariant, deleteProductImage, setPrimaryImage, updateProductDetails, updateVariant, uploadProductImage } from "../actions";

export default async function ProductEditor({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; updated?: string; error?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const { supabase } = await requireAdmin();
  const [{ data: product }, { data: categories }] = await Promise.all([
    supabase.from("products").select("id,title,slug,description,short_description,category_id,status,is_featured,image_url,weight_oz,tax_code,seo_title,seo_description,product_images(id,storage_path,public_url,alt_text,sort_order),product_variants(id,sku,title,price_amount,compare_at_amount,status,option_values,inventory(available,reserved),supplier_mappings(id,supplier_code,supplier_sku,landed_cost_amount,channel_approved,evidence_checked_at))").eq("id", id).single(),
    supabase.from("categories").select("id,name").order("sort_order").order("name"),
  ]);
  if (!product) notFound();
  const saveDetails = updateProductDetails.bind(null, product.id);
  const add = addVariant.bind(null, product.id);
  const upload = uploadProductImage.bind(null, product.id);
  const images = [...(product.product_images || [])].sort((a, b) => a.sort_order - b.sort_order);
  return <><div className="admin-title"><div><p>Product editor</p><h1>{product.title}</h1></div><Link className="admin-secondary" href="/admin/products"><ArrowLeft size={14} /> Products</Link></div>
    {query.created ? <div className="notice success">Product draft created. Add media and review every field before publishing.</div> : null}{query.updated ? <div className="notice success">Product changes saved.</div> : null}{query.error ? <div className="notice error">Change failed. Check unique values, valid pricing, file type, and supplier fields.</div> : null}
    <section className="admin-panel"><div className="panel-heading"><div><p>Core product</p><h2>Content, category and publishing</h2></div><span>Publishing exposes only published variants to customers.</span></div><form action={saveDetails} className="admin-form">
      <label>Product title<input name="title" defaultValue={product.title} required minLength={2} maxLength={160} /></label><label>URL slug<input name="slug" defaultValue={product.slug} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label>Category<select name="categoryId" defaultValue={product.category_id || ""}><option value="">Uncategorized</option>{categories?.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label>
      <label className="field-wide">Short description<input name="shortDescription" defaultValue={product.short_description} maxLength={300} /></label><label className="field-wide">Full description<textarea name="description" defaultValue={product.description} rows={6} /></label>
      <label>Weight (oz)<input name="weightOz" type="number" min="0.1" max="2400" step="0.1" defaultValue={product.weight_oz || 16} required /></label><label>Stripe tax code<input name="taxCode" pattern="txcd_[0-9]{8}" defaultValue={product.tax_code || "txcd_99999999"} required /></label><label>Status<select name="status" defaultValue={product.status}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label>
      <label className="admin-check"><input name="featured" type="checkbox" defaultChecked={product.is_featured} /> Featured product</label><label>SEO title<input name="seoTitle" defaultValue={product.seo_title || ""} maxLength={70} /></label><label className="field-wide">SEO description<textarea name="seoDescription" defaultValue={product.seo_description || ""} maxLength={170} rows={3} /></label><div className="field-wide"><button className="admin-primary" type="submit">Save product details</button></div>
    </form></section>
    <section className="admin-panel" id="media"><div className="panel-heading"><div><p>Product media</p><h2>Images and gallery</h2></div><span>JPG, PNG, WebP or AVIF · maximum 5 MB.</span></div><div className="product-media-admin">{images.map((image) => { const primary = product.image_url === image.public_url; const makePrimary = setPrimaryImage.bind(null, product.id, image.id); const remove = deleteProductImage.bind(null, product.id, image.id); return <article key={image.id}><img src={image.public_url} alt={image.alt_text} /><p>{image.alt_text || "No alt text"}</p><div>{primary ? <span className="status-pill published"><Star size={11} /> Primary</span> : <form action={makePrimary}><button className="admin-secondary" type="submit">Set primary</button></form>}<form action={remove}><button className="admin-danger" type="submit"><Trash2 size={13} /> Remove</button></form></div></article>; })}</div><form action={upload} className="media-upload-form"><ImagePlus size={22} /><label>Image<input name="image" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required /></label><label>Alt text<input name="altText" maxLength={180} placeholder="Describe the product image" /></label><button className="admin-primary" type="submit">Upload image</button></form></section>
    <section className="admin-panel" id="variants"><div className="panel-heading"><div><p>Variants</p><h2>Pricing, options, stock and supplier</h2></div><span>Every price is stored as integer cents and rechecked during checkout.</span></div><div className="variant-admin-list">{product.product_variants?.map((variant: any) => { const supplier = variant.supplier_mappings?.[0]; const saveVariant = updateVariant.bind(null, product.id, variant.id); return <form action={saveVariant} key={variant.id} className="variant-admin-form"><div className="variant-admin-heading"><b>{variant.title}</b><span className={`status-pill ${variant.status}`}>{variant.status}</span></div><label>Variant name<input name="variantTitle" defaultValue={variant.title} required /></label><label>SKU<input name="sku" defaultValue={variant.sku} required /></label><label>Color<input name="color" defaultValue={variant.option_values?.color || ""} /></label><label>Size<input name="size" defaultValue={variant.option_values?.size || ""} /></label><label>Price<input name="price" type="number" min="0" step="0.01" defaultValue={(variant.price_amount / 100).toFixed(2)} required /></label><label>Compare-at<input name="compareAt" type="number" min="0" step="0.01" defaultValue={variant.compare_at_amount === null ? "" : (variant.compare_at_amount / 100).toFixed(2)} /></label><label>Stock<input name="inventory" type="number" min="0" step="1" defaultValue={variant.inventory?.available ?? 0} required /><small>{variant.inventory?.reserved || 0} reserved</small></label><label>Status<select name="status" defaultValue={variant.status}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Supplier code<input name="supplierCode" defaultValue={supplier?.supplier_code || ""} /></label><label>Supplier SKU<input name="supplierSku" defaultValue={supplier?.supplier_sku || ""} /></label><label>Landed cost<input name="landedCost" type="number" min="0" step="0.01" defaultValue={supplier?.landed_cost_amount === null || supplier?.landed_cost_amount === undefined ? "" : (supplier.landed_cost_amount / 100).toFixed(2)} /></label><label className="admin-check"><input name="channelApproved" type="checkbox" defaultChecked={supplier?.channel_approved || false} /> Channel approved</label><button className="admin-primary" type="submit">Save variant</button></form>; })}</div>
      <div className="variant-create"><h3>Add another variant</h3><form action={add} className="admin-form"><label>Variant name<input name="variantTitle" required placeholder="Large / Black" /></label><label>SKU<input name="sku" required /></label><label>Color<input name="color" /></label><label>Size<input name="size" /></label><label>Price<input name="price" type="number" min="0" step="0.01" required /></label><label>Compare-at<input name="compareAt" type="number" min="0" step="0.01" /></label><label>Stock<input name="inventory" type="number" min="0" step="1" defaultValue="0" required /></label><label>Supplier code<input name="supplierCode" /></label><label>Supplier SKU<input name="supplierSku" /></label><label>Landed cost<input name="landedCost" type="number" min="0" step="0.01" /></label><label className="admin-check"><input name="channelApproved" type="checkbox" /> Channel approved</label><div className="field-wide"><button className="admin-primary" type="submit">Add variant</button></div></form></div>
    </section></>;
}
