import { requireAdmin } from "@/lib/auth";
import { createProduct, updateProduct } from "./actions";

export default async function AdminProducts({ searchParams }: { searchParams: Promise<{ error?: string; created?: string; updated?: string }> }) {
  const params = await searchParams;
  const { supabase } = await requireAdmin();
  const { data } = await supabase.from("products").select("id,title,slug,status,created_at,product_variants(sku,price_amount,inventory(available))").order("created_at", { ascending: false }).limit(50);
  return <><div className="admin-title"><div><p>Catalog</p><h1>Products</h1></div></div>{params.created ? <div className="notice success">Draft product created.</div> : null}{params.updated ? <div className="notice success">Catalog record updated.</div> : null}{params.error ? <div className="notice error">Catalog change failed. Check unique values and valid fields.</div> : null}<section className="admin-panel"><div className="panel-heading"><div><p>Current catalog</p><h2>{data?.length || 0} products</h2></div></div><div className="catalog-admin-list">{data?.length ? data.map((product: any) => { const variant = product.product_variants?.[0]; const update = updateProduct.bind(null, product.id); return <form action={update} className="catalog-admin-row" key={product.id}><div><b>{product.title}</b><small>/{product.slug} · {variant?.sku || "No SKU"}</small></div><label>Price (USD)<input name="price" type="number" min="0" step="0.01" defaultValue={((variant?.price_amount || 0) / 100).toFixed(2)} required /></label><label>Stock<input name="inventory" type="number" min="0" step="1" defaultValue={variant?.inventory?.available ?? 0} required /></label><label>Status<select name="status" defaultValue={product.status}><option value="draft">Draft</option><option value="review">Review</option><option value="published">Published</option><option value="archived">Archived</option></select></label><button className="admin-secondary" type="submit">Save</button></form>; }) : <p className="admin-empty">No products yet. Add the first verified item below.</p>}</div></section><section className="admin-panel" id="new"><div className="panel-heading"><div><p>New product</p><h2>Create a secure catalog draft</h2></div><span>Prices are stored in cents on the server.</span></div><form action={createProduct} className="admin-form"><label>Product title<input name="title" required minLength={2} /></label><label>URL slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="dog-car-seat-cover" /></label><label>SKU<input name="sku" required minLength={2} /></label><label>Price (USD)<input name="price" type="number" required min="0" step="0.01" /></label><label>Opening inventory<input name="inventory" type="number" required min="0" step="1" defaultValue="0" /></label><label>Image URL<input name="imageUrl" type="url" /></label><label className="field-wide">Description<textarea name="description" rows={5} /></label><div className="field-wide"><button className="admin-primary" type="submit">Create draft</button></div></form></section></>;
}
