import { requireAdmin } from "@/lib/auth";
import { createCategory, toggleCategory } from "./actions";

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<{ created?: string; updated?: string; error?: string }> }) {
  const params = await searchParams;
  const { supabase } = await requireAdmin();
  const { data } = await supabase.from("categories").select("id,name,slug,description,is_active,sort_order").order("sort_order").order("name");
  return <><div className="admin-title"><div><p>Catalog structure</p><h1>Categories</h1></div></div>{params.created || params.updated ? <div className="notice success">Category saved.</div> : null}{params.error ? <div className="notice error">Category change failed. Check the name and unique slug.</div> : null}<section className="admin-panel"><div className="panel-heading"><div><p>Navigation</p><h2>{data?.length || 0} categories</h2></div></div><div className="catalog-admin-list">{data?.length ? data.map((category) => { const toggle = toggleCategory.bind(null, category.id); return <form action={toggle} className="category-admin-row" key={category.id}><div><b>{category.name}</b><small>/{category.slug}</small><p>{category.description || "No description yet."}</p></div><input name="isActive" type="hidden" value={category.is_active ? "false" : "true"} /><span className={`status-pill ${category.is_active ? "published" : "archived"}`}>{category.is_active ? "active" : "hidden"}</span><button className="admin-secondary" type="submit">{category.is_active ? "Hide" : "Activate"}</button></form>; }) : <p className="admin-empty">No categories yet.</p>}</div></section><section className="admin-panel" id="new"><div className="panel-heading"><div><p>New category</p><h2>Add storefront navigation</h2></div></div><form action={createCategory} className="admin-form"><label>Name<input name="name" required minLength={2} /></label><label>URL slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="travel" /></label><label className="field-wide">Description<textarea name="description" rows={4} /></label><div className="field-wide"><button className="admin-primary" type="submit">Create category</button></div></form></section></>;
}
