// POST /api/media/generate
//
// Generates REAL images/videos server-side (not fake placeholders) and
// uploads the result into the Supabase `product-media` bucket, returning a
// durable public URL ready to use in marketing copy, products or emails.
//
// Supported:
//   { type: 'image', provider: 'openai', prompt }  → OpenAI gpt-image-1
//   { type: 'image', provider: 'gemini', prompt }  → Google Imagen 3
//   { type: 'video', provider: 'gemini', prompt }  → Google Veo 3 (long-running, polled)
//
// Keys: OPENAI_API_KEY / GEMINI_API_KEY from env, or owner-attached via
// Settings → AI & Scraping Keys (AI_KEY_OPENAI / AI_KEY_GEMINI). env wins.
//
// SECURITY:
//   - Admin-only + rate limited. Prompt length capped.
//   - Keys never leave the server. Generated bytes are size-checked before
//     upload. Missing keys/config fail closed with an honest error.
// ============================================================================
import type { IncomingMessage, ServerResponse } from 'node:http';
import { sendJson, rateLimited, clientIp, readJsonBody, resolveProviderKey, isConfiguredFull } from '../_lib/providers.js';
import { requireAdmin } from '../_lib/auth.js';

const BUCKET = 'product-media';
const MAX_PROMPT = 4000;
const MAX_BYTES = 12 * 1024 * 1024; // 12 MB decoded (video clips can be large)
const POLL_TIMEOUT_MS = 120_000;
const POLL_INTERVAL_MS = 4_000;

function supabaseConfig(): { url: string; serviceRole: string } | null {
  const url = (process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || '').trim().replace(/\/$/, '');
  const serviceRole = (process.env.SUPABASE_SERVICE_ROLE_KEY || '').trim();
  return url && serviceRole ? { url, serviceRole } : null;
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 50) || 'media';
}

async function uploadBytes(cfg: { url: string; serviceRole: string }, bytes: Uint8Array, contentType: string, filename: string): Promise<string> {
  const res = await fetch(`${cfg.url}/storage/v1/object/${BUCKET}/${filename}`, {
    method: 'POST',
    headers: {
      apikey: cfg.serviceRole,
      Authorization: `Bearer ${cfg.serviceRole}`,
      'Content-Type': contentType,
      'x-upsert': 'true',
    },
    body: bytes as unknown as BodyInit,
    signal: AbortSignal.timeout(30_000),
  });
  if (!res.ok) throw new Error(`Storage upload failed (HTTP ${res.status})`);
  return `${cfg.url}/storage/v1/object/public/${BUCKET}/${filename}`;
}

/** OpenAI gpt-image-1 → base64 PNG bytes. */
async function generateOpenAiImage(key: string, prompt: string): Promise<{ bytes: Uint8Array; contentType: string }> {
  const r = await fetch('https://api.openai.com/v1/images/generations', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${key}` },
    body: JSON.stringify({ model: 'gpt-image-1', prompt, n: 1, size: '1024x1024' }),
    signal: AbortSignal.timeout(90_000),
  });
  const d = await r.json().catch(() => ({})) as { error?: { message?: string }; data?: Array<{ b64_json?: string; url?: string }> };
  if (!r.ok) throw new Error(`OpenAI image error (HTTP ${r.status})${d.error?.message ? `: ${d.error.message.slice(0, 140)}` : ''}`);
  const item = d.data?.[0];
  if (item?.b64_json) return { bytes: Buffer.from(item.b64_json, 'base64'), contentType: 'image/png' };
  if (item?.url) {
    const img = await fetch(item.url, { signal: AbortSignal.timeout(60_000) });
    if (!img.ok) throw new Error('OpenAI returned an image URL that could not be downloaded.');
    return { bytes: new Uint8Array(await img.arrayBuffer()), contentType: img.headers.get('content-type') || 'image/png' };
  }
  throw new Error('OpenAI returned no image.');
}

// Gemini image-capable models that speak generateContent (Imagen's legacy
// :predict API no longer exists on v1beta). Queried live so the best model is
// chosen; falls back to the widely-available gemini-2.5-flash-image.
const GEMINI_IMAGE_MODELS = [
  'gemini-3.1-flash-image',
  'gemini-2.5-flash-image',
  'gemini-3-pro-image',
  'gemini-3-pro-image-preview',
];

/** Resolve the first image-capable model available on this key. */
async function resolveGeminiImageModel(key: string): Promise<string> {
  try {
    const r = await fetch('https://generativelanguage.googleapis.com/v1beta/models?key=' + encodeURIComponent(key), { signal: AbortSignal.timeout(15_000) });
    if (r.ok) {
      const d = await r.json().catch(() => null) as { models?: Array<{ name: string }> } | null;
      const available = new Set((d?.models || []).map((m) => m.name.replace(/^models\//, '')));
      for (const m of GEMINI_IMAGE_MODELS) if (available.has(m)) return m;
    }
  } catch { /* fall through to default */ }
  return GEMINI_IMAGE_MODELS[1]; // gemini-2.5-flash-image
}

/** Google Gemini image model (generateContent, IMAGE modality) → image bytes. */
async function generateGeminiImage(key: string, prompt: string): Promise<{ bytes: Uint8Array; contentType: string }> {
  const model = await resolveGeminiImageModel(key);
  const r = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=` + encodeURIComponent(key), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { responseModalities: ['IMAGE'] },
    }),
    signal: AbortSignal.timeout(120_000),
  });
  const d = await r.json().catch(() => ({})) as { error?: { message?: string }; candidates?: Array<{ content?: { parts?: Array<{ inlineData?: { mimeType?: string; data?: string } }> } }> };
  if (!r.ok) throw new Error(`Gemini image error (HTTP ${r.status})${d.error?.message ? `: ${d.error.message.slice(0, 140)}` : ''}`);
  const img = d.candidates?.[0]?.content?.parts?.find((p) => p.inlineData?.data);
  if (!img?.inlineData?.data) throw new Error('Gemini returned no image.');
  return { bytes: Buffer.from(img.inlineData.data, 'base64'), contentType: img.inlineData.mimeType || 'image/png' };
}

/** Google Veo (3.1+) → long-running operation, polled until the clip is ready. */
async function generateGeminiVideo(key: string, prompt: string): Promise<{ bytes: Uint8Array; contentType: string }> {
  const start = await fetch('https://generativelanguage.googleapis.com/v1beta/models/veo-3.1-generate-preview:predictLongRunning?key=' + encodeURIComponent(key), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ instances: [{ prompt }] }),
    signal: AbortSignal.timeout(60_000),
  });
  const startData = await start.json().catch(() => ({})) as { error?: { message?: string }; name?: string };
  if (!start.ok) throw new Error(`Veo start error (HTTP ${start.status})${startData.error?.message ? `: ${startData.error.message.slice(0, 140)}` : ''}`);
  const opName = startData.name;
  if (!opName) throw new Error('Veo did not return an operation id.');

  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
    const poll = await fetch(`https://generativelanguage.googleapis.com/v1beta/${opName}?key=${encodeURIComponent(key)}`, { signal: AbortSignal.timeout(30_000) });
    const d = await poll.json().catch(() => ({})) as {
      error?: { message?: string };
      done?: boolean;
      response?: { generatedVideos?: Array<{ video?: { videoBytesBase64?: string; uri?: string } }> };
    };
    if (!poll.ok) throw new Error(`Veo poll error (HTTP ${poll.status})${d.error?.message ? `: ${d.error.message.slice(0, 140)}` : ''}`);
    if (d.done) {
      const clip = d.response?.generatedVideos?.[0]?.video;
      if (clip?.videoBytesBase64) return { bytes: Buffer.from(clip.videoBytesBase64, 'base64'), contentType: 'video/mp4' };
      if (clip?.uri) {
        const vid = await fetch(clip.uri, { signal: AbortSignal.timeout(60_000) });
        if (!vid.ok) throw new Error('Veo produced a clip that could not be downloaded.');
        return { bytes: new Uint8Array(await vid.arrayBuffer()), contentType: 'video/mp4' };
      }
      throw new Error('Veo finished without a video clip.');
    }
  }
  throw new Error('Veo generation timed out (2 min). Try a shorter prompt.');
}

export default async function handler(req: IncomingMessage, res: ServerResponse): Promise<void> {
  if (req.method !== 'POST') {
    sendJson(res, 405, { error: 'Method not allowed' });
    return;
  }
  if (rateLimited(clientIp(req))) {
    sendJson(res, 429, { error: 'Too many requests — slow down.' });
    return;
  }
  if (!(await requireAdmin(req, res))) return;

  let body: { type?: string; provider?: string; prompt?: string } = {};
  try {
    body = await readJsonBody(req);
  } catch (e) {
    sendJson(res, 400, { error: (e as Error).message });
    return;
  }
  const type = String(body.type || '');
  const provider = String(body.provider || '');
  const prompt = String(body.prompt || '').trim();

  if (type !== 'image' && type !== 'video') {
    sendJson(res, 400, { error: 'type must be "image" or "video".' });
    return;
  }
  if (!prompt || prompt.length > MAX_PROMPT) {
    sendJson(res, 400, { error: `prompt is required (max ${MAX_PROMPT} chars).` });
    return;
  }
  const allowed = type === 'image' ? ['openai', 'gemini'] : ['gemini'];
  if (!allowed.includes(provider)) {
    sendJson(res, 400, { error: `provider must be one of: ${allowed.join(', ')} for ${type} generation.` });
    return;
  }
  if (!(await isConfiguredFull(provider))) {
    sendJson(res, 501, { error: `${provider} not configured on server. Attach an API key in AI Hub → Attach Key (or set ${provider === 'openai' ? 'OPENAI_API_KEY' : 'GEMINI_API_KEY'} env var), then retry.` });
    return;
  }
  const cfg = supabaseConfig();
  if (!cfg) {
    sendJson(res, 502, { error: 'Media storage is unavailable (Supabase service role not configured).' });
    return;
  }
  const key = await resolveProviderKey(provider);

  try {
    const out = type === 'image'
      ? (provider === 'openai' ? await generateOpenAiImage(key, prompt) : await generateGeminiImage(key, prompt))
      : await generateGeminiVideo(key, prompt);
    if (out.bytes.length > MAX_BYTES) throw new Error('Generated media exceeds the size limit.');
    const ext = out.contentType.includes('video') ? 'mp4' : 'png';
    const filename = `ai-${slugify(prompt)}-${Date.now()}.${ext}`;
    const url = await uploadBytes(cfg, out.bytes, out.contentType, filename);
    sendJson(res, 200, { ok: true, type, provider, prompt, url, contentType: out.contentType, bytes: out.bytes.length });
  } catch (e) {
    sendJson(res, 502, { ok: false, error: (e as Error).message });
  }
}